name: Release Please

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release-please:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      releases_created: ${{ steps.release-please.outputs.releases_created }}
      tag_name: ${{ steps.release-please.outputs.tag_name }}
    steps:
      - name: Release Please
        id: release-please
        uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5
